-- Create the service_suggestions table
CREATE TABLE IF NOT EXISTS public.service_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start_date DATE NOT NULL,
    view_mode TEXT NOT NULL DEFAULT 'carousel',
    content JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add a unique constraint so there is only one suggestion per week
ALTER TABLE public.service_suggestions ADD CONSTRAINT service_suggestions_week_start_date_key UNIQUE (week_start_date);

-- Enable RLS
ALTER TABLE public.service_suggestions ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated and anonymous access since this app uses custom auth logic via `app_users`
CREATE POLICY "Enable all operations for all"
    ON public.service_suggestions
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.service_suggestions TO anon, authenticated;
