DROP TABLE IF EXISTS public.service_suggestions;

CREATE TABLE public.service_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    show_title_on_home BOOLEAN NOT NULL DEFAULT false,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    last_used_at TIMESTAMP WITH TIME ZONE,
    is_visible BOOLEAN NOT NULL DEFAULT false,
    content JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.service_suggestions ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated and anonymous access
CREATE POLICY "Enable all operations for all"
    ON public.service_suggestions
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.service_suggestions TO anon, authenticated;
