-- 건물은 세대의 기본 용도를 갖고, 다른 세대만 usage_type을 저장한다.
-- 식당은 항상 상가로 저장하며 읽기 규칙도 같이 방어한다.
alter table public.units
  add column if not exists usage_type text
  check (usage_type is null or usage_type in ('주택', '상가'));

update public.units
set usage_type = '상가'
where coalesce(is_restaurant, false) is true
  and usage_type is distinct from '상가';

-- warning이 담던 건물 전체 방문금지 의미를 명시적인 상태로 옮긴다.
-- 예전 앱과 CSV 호환을 위해 warning 컬럼은 이 단계에서 지우지 않는다.
alter table public.buildings
  add column if not exists access_status text not null default 'normal'
  check (access_status in ('normal', 'blocked'));

update public.buildings
set access_status = 'blocked'
where coalesce(warning, false) is true
   or exists (
     select 1 from public.units u
     where u.building_id = buildings.id and btrim(u.number) = '출입불가'
   );

create table if not exists public.building_access_events (
  id bigint generated by default as identity primary key,
  building_id integer not null references public.buildings(id) on delete cascade,
  action text not null check (action in ('blocked', 'reopened')),
  visitor_name text not null,
  visited_at date not null default current_date,
  time_slot text check (time_slot is null or time_slot in ('오전', '오후', '저녁')),
  memo text,
  source_visit_history_id integer unique,
  created_at timestamptz not null default now()
);

alter table public.building_access_events enable row level security;
revoke all on public.building_access_events from public, anon, authenticated;
grant select on public.building_access_events to anon, authenticated;

drop policy if exists building_access_events_select on public.building_access_events;
create policy building_access_events_select on public.building_access_events
  for select to anon, authenticated using (true);

-- 기존 `출입불가` 세대의 방문기록을 건물 이력으로 먼저 복사한다.
-- 원본 세대와 기록은 운영 검증 후 별도 마이그레이션에서 제거한다.
insert into public.building_access_events (
  building_id, action, visitor_name, visited_at, time_slot, memo,
  source_visit_history_id, created_at
)
select
  u.building_id, 'blocked', vh.visitor_name, vh.visited_at, vh.time_slot, vh.memo,
  vh.id, vh.created_at
from public.units u
join public.visit_histories vh on vh.unit_id = u.id
where btrim(u.number) = '출입불가'
on conflict (source_visit_history_id) do nothing;

create or replace function public.set_building_access_tx(
  p_token uuid,
  p_building_id integer,
  p_blocked boolean,
  p_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id integer;
  v_actor_name text;
  v_status text := case when p_blocked then 'blocked' else 'normal' end;
  v_action text := case when p_blocked then 'blocked' else 'reopened' end;
begin
  v_actor_id := public.verify_session(p_token);
  select name into v_actor_name from public.app_users where id = v_actor_id;
  if v_actor_name is null then raise exception '사용자를 확인할 수 없습니다'; end if;

  update public.buildings
  set access_status = v_status,
      warning = p_blocked
  where id = p_building_id
    and access_status is distinct from v_status;

  if not found then
    if not exists (select 1 from public.buildings where id = p_building_id) then
      raise exception '건물을 찾을 수 없습니다';
    end if;
    return jsonb_build_object('ok', true, 'changed', false, 'status', v_status);
  end if;

  insert into public.building_access_events (
    building_id, action, visitor_name, visited_at, memo
  ) values (
    p_building_id, v_action, v_actor_name, current_date, nullif(btrim(p_note), '')
  );

  return jsonb_build_object('ok', true, 'changed', true, 'status', v_status);
end;
$$;

revoke all on function public.set_building_access_tx(uuid,integer,boolean,text)
  from public, anon, authenticated;
grant execute on function public.set_building_access_tx(uuid,integer,boolean,text)
  to anon, authenticated;

-- 건물 기본 용도를 바꾸면 null 세대의 실제 용도도 함께 바뀐다.
-- 화면만 숨기지 말고 DB에서 관리자·인도자만 허용한다.
create or replace function public.session_can_change_building_type()
returns boolean
language sql stable security definer
set search_path = ''
as $$
  select coalesce(private.request_session_role() in ('leader', 'admin', 'developer'), false)
$$;
revoke all on function public.session_can_change_building_type() from public;
grant execute on function public.session_can_change_building_type() to anon, authenticated;

create or replace function public.guard_building_type_change()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.type is not distinct from old.type then return new; end if;
  if current_user in ('postgres', 'supabase_admin', 'service_role') then return new; end if;
  if not public.session_can_change_building_type() then
    raise exception '건물 유형을 변경할 권한이 없습니다' using errcode = '42501';
  end if;
  return new;
end;
$$;

revoke all on function public.guard_building_type_change() from public, anon, authenticated;
drop trigger if exists guard_building_type_change_trigger on public.buildings;
create trigger guard_building_type_change_trigger
before update of type on public.buildings
for each row execute function public.guard_building_type_change();

notify pgrst, 'reload schema';
