-- 정기방문 종료와 장소 수정 요청.
-- 삭제 대신 종료 상태를 남겨 방문 기록을 보존한다.

alter table public.return_visits
  add column if not exists ended_at timestamptz,
  add column if not exists ended_by_name text,
  add column if not exists end_reason text;

create table if not exists public.place_change_requests (
  id bigint generated by default as identity primary key,
  request_type text not null check (request_type in (
    'building_missing', 'unit_missing', 'details_wrong', 'duplicate_place', 'other'
  )),
  building_id bigint references public.buildings(id) on delete set null,
  unit_id bigint references public.units(id) on delete set null,
  return_visit_id bigint references public.return_visits(id) on delete set null,
  building_name text,
  address text,
  unit_number text,
  note text not null default '',
  requested_by_id integer references public.app_users(id) on delete set null,
  requested_by_name text not null,
  status text not null default 'pending' check (status in ('pending', 'completed', 'rejected')),
  reviewed_by_name text,
  review_note text not null default '',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists place_change_requests_pending_idx
  on public.place_change_requests (created_at desc) where status = 'pending';

alter table public.place_change_requests enable row level security;
revoke truncate, references, trigger on public.place_change_requests from public, anon, authenticated;

drop policy if exists place_change_requests_select on public.place_change_requests;
create policy place_change_requests_select on public.place_change_requests
  for select to anon, authenticated
  using (
    requested_by_id = (select private.request_session_user_id())
    or (select private.request_is_admin())
  );

-- 쓰기는 아래 definer 함수만 담당한다.
revoke insert, update, delete on public.place_change_requests from public, anon, authenticated;

create or replace function public.submit_place_change_request_tx(
  p_token uuid,
  p_request_type text,
  p_building_id bigint default null,
  p_unit_id bigint default null,
  p_return_visit_id bigint default null,
  p_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id integer;
  v_actor_name text;
  v_building_id bigint := p_building_id;
  v_unit_id bigint := p_unit_id;
  v_building_name text;
  v_address text;
  v_unit_number text;
  v_id bigint;
begin
  v_actor_id := public.verify_session(p_token);
  select name into v_actor_name from public.app_users where id = v_actor_id;
  if coalesce(btrim(v_actor_name), '') = '' then
    raise exception '로그인 사용자를 찾을 수 없습니다' using errcode = '42501';
  end if;
  if p_request_type not in ('building_missing', 'unit_missing', 'details_wrong', 'duplicate_place', 'other') then
    raise exception '요청 종류가 올바르지 않습니다';
  end if;

  if p_return_visit_id is not null then
    select coalesce(v_building_id, rv.building_id), coalesce(v_unit_id, rv.unit_id)
      into v_building_id, v_unit_id
    from public.return_visits rv where rv.id = p_return_visit_id;
  end if;
  if v_unit_id is not null then
    select u.number, b.id, b.name, b.address
      into v_unit_number, v_building_id, v_building_name, v_address
    from public.units u join public.buildings b on b.id = u.building_id
    where u.id = v_unit_id;
  elsif v_building_id is not null then
    select b.name, b.address into v_building_name, v_address
    from public.buildings b where b.id = v_building_id;
  elsif p_return_visit_id is not null then
    select rv.display_name, rv.address, rv.unit_number
      into v_building_name, v_address, v_unit_number
    from public.return_visits rv where rv.id = p_return_visit_id;
  end if;

  insert into public.place_change_requests (
    request_type, building_id, unit_id, return_visit_id,
    building_name, address, unit_number, note,
    requested_by_id, requested_by_name
  ) values (
    p_request_type, v_building_id, v_unit_id, p_return_visit_id,
    v_building_name, v_address, v_unit_number, left(btrim(coalesce(p_note, '')), 1000),
    v_actor_id, v_actor_name
  ) returning id into v_id;

  return jsonb_build_object('ok', true, 'id', v_id);
end;
$$;

revoke all on function public.submit_place_change_request_tx(uuid,text,bigint,bigint,bigint,text)
  from public, anon, authenticated;
grant execute on function public.submit_place_change_request_tx(uuid,text,bigint,bigint,bigint,text)
  to anon, authenticated;

create or replace function public.end_return_visit_tx(
  p_token uuid,
  p_return_visit_id bigint,
  p_reason text,
  p_issue_type text default null,
  p_issue_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id integer;
  v_actor_name text;
  v_actor_role text;
  v_assignee text;
  v_unit_id bigint;
  v_ended_at timestamptz;
  v_request jsonb;
begin
  v_actor_id := public.verify_session(p_token);
  select name, role into v_actor_name, v_actor_role from public.app_users where id = v_actor_id;
  if p_reason not in ('no_longer_assigned', 'needs_reassignment', 'no_longer_target') then
    raise exception '종료 사유가 올바르지 않습니다';
  end if;

  select assigned_user_name, unit_id, ended_at
    into v_assignee, v_unit_id, v_ended_at
  from public.return_visits
  where id = p_return_visit_id
  for update;
  if not found then raise exception '정기방문을 찾을 수 없습니다'; end if;
  if v_ended_at is not null then
    return jsonb_build_object('ok', true, 'already_ended', true);
  end if;
  if btrim(coalesce(v_assignee, '')) <> btrim(coalesce(v_actor_name, ''))
     and not coalesce(v_actor_role in ('admin', 'developer', 'leader'), false) then
    raise exception '본인의 정기방문만 종료할 수 있습니다' using errcode = '42501';
  end if;

  if v_unit_id is not null then
    -- 다른 담당자로 이미 바뀐 행을 예전 활동 기록이 지우지 않게 한다.
    delete from public.regular_visits
    where unit_id = v_unit_id
      and btrim(visitor_name) = btrim(coalesce(v_assignee, ''));
  end if;

  update public.return_visits
  set ended_at = now(), ended_by_name = v_actor_name, end_reason = p_reason
  where id = p_return_visit_id;

  if p_issue_type is not null then
    v_request := public.submit_place_change_request_tx(
      p_token, p_issue_type, null, null, p_return_visit_id, p_issue_note
    );
  end if;

  return jsonb_build_object('ok', true, 'request_id', v_request -> 'id');
end;
$$;

revoke all on function public.end_return_visit_tx(uuid,bigint,text,text,text)
  from public, anon, authenticated;
grant execute on function public.end_return_visit_tx(uuid,bigint,text,text,text)
  to anon, authenticated;

create or replace function public.review_place_change_request_tx(
  p_token uuid,
  p_request_id bigint,
  p_status text,
  p_review_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id integer;
  v_actor_name text;
  v_actor_role text;
begin
  v_actor_id := public.verify_session(p_token);
  select name, role into v_actor_name, v_actor_role from public.app_users where id = v_actor_id;
  if not coalesce(v_actor_role in ('admin', 'developer'), false) then
    raise exception '관리자만 요청을 처리할 수 있습니다' using errcode = '42501';
  end if;
  if p_status not in ('completed', 'rejected') then raise exception '처리 상태가 올바르지 않습니다'; end if;

  update public.place_change_requests
  set status = p_status,
      reviewed_by_name = v_actor_name,
      review_note = left(btrim(coalesce(p_review_note, '')), 1000),
      reviewed_at = now()
  where id = p_request_id and status = 'pending';
  if not found then raise exception '처리할 요청을 찾을 수 없습니다'; end if;
  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.review_place_change_request_tx(uuid,bigint,text,text)
  from public, anon, authenticated;
grant execute on function public.review_place_change_request_tx(uuid,bigint,text,text)
  to anon, authenticated;

-- 활성 목록은 종료되지 않은 행만 한 세대에 하나다.
drop index if exists public.return_visits_unit_id_unique;
create unique index return_visits_unit_id_unique
  on public.return_visits (unit_id)
  where unit_id is not null and ended_at is null;

-- 종료된 항목을 같은 세대에서 다시 맡으면 기존 기록을 살려 재활성화한다.
create or replace function public.create_return_visit_tx(
  p_token uuid,
  p_display_name text,
  p_address text default '',
  p_memo text default '',
  p_first_result text default null,
  p_unit_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id integer;
  v_actor_name text;
  v_building_id bigint;
  v_building_address text;
  v_unit_number text;
  v_regular_visitor text;
  v_existing_assignee text;
  v_existing_ended_at timestamptz;
  v_return_visit_id bigint;
  v_created boolean := false;
  v_reactivated boolean := false;
  v_now timestamptz := now();
  v_memo text := btrim(coalesce(p_memo, ''));
begin
  v_actor_id := public.verify_session(p_token);
  select name into v_actor_name from public.app_users where id = v_actor_id;
  if coalesce(btrim(v_actor_name), '') = '' then
    raise exception '로그인 사용자를 찾을 수 없습니다' using errcode = '42501';
  end if;
  if coalesce(btrim(p_display_name), '') = '' then raise exception '정기방문 이름을 입력하세요'; end if;
  if p_first_result is not null and p_first_result not in ('만남', '부재') then
    raise exception '첫 방문 결과가 올바르지 않습니다';
  end if;

  if p_unit_id is not null then
    select u.building_id, u.number, b.address
      into v_building_id, v_unit_number, v_building_address
    from public.units u join public.buildings b on b.id = u.building_id
    where u.id = p_unit_id
    for update of u, b;
    if not found then raise exception '연결할 세대를 찾을 수 없습니다'; end if;

    select visitor_name into v_regular_visitor
    from public.regular_visits where unit_id = p_unit_id for update;

    select id, assigned_user_name, ended_at
      into v_return_visit_id, v_existing_assignee, v_existing_ended_at
    from public.return_visits
    where unit_id = p_unit_id
    order by ended_at nulls first, created_at desc
    limit 1
    for update;

    if v_return_visit_id is not null and v_existing_ended_at is null
       and btrim(coalesce(v_existing_assignee, '')) <> btrim(v_actor_name) then
      raise exception '이미 %님이 활동 정기방문을 담당하고 있습니다',
        coalesce(nullif(btrim(v_existing_assignee), ''), '다른 사용자');
    end if;
    if v_regular_visitor is not null and btrim(v_regular_visitor) <> btrim(v_actor_name)
       and v_existing_ended_at is null then
      raise exception '이미 %님이 정기방문을 담당하고 있습니다', v_regular_visitor;
    end if;

    insert into public.regular_visits (unit_id, visitor_name, registered_at)
    values (p_unit_id, v_actor_name, v_now)
    on conflict (unit_id) do update
      set visitor_name = excluded.visitor_name, registered_at = excluded.registered_at;

    if v_return_visit_id is null then
      insert into public.return_visits (
        unit_id, building_id, display_name, nickname, address, unit_number,
        assigned_user_name, created_by, created_at
      ) values (
        p_unit_id, v_building_id, btrim(p_display_name), btrim(p_display_name),
        coalesce(v_building_address, ''), coalesce(v_unit_number, ''),
        v_actor_name, v_actor_name, v_now
      ) returning id into v_return_visit_id;
      v_created := true;
    elsif v_existing_ended_at is not null then
      update public.return_visits
      set building_id = v_building_id,
          display_name = btrim(p_display_name),
          nickname = btrim(p_display_name),
          address = coalesce(v_building_address, ''),
          unit_number = coalesce(v_unit_number, ''),
          assigned_user_name = v_actor_name,
          ended_at = null,
          ended_by_name = null,
          end_reason = null
      where id = v_return_visit_id;
      v_reactivated := true;
    end if;
  else
    insert into public.return_visits (
      unit_id, building_id, display_name, nickname, address, unit_number,
      assigned_user_name, created_by, created_at
    ) values (
      null, null, btrim(p_display_name), btrim(p_display_name), btrim(coalesce(p_address, '')), '',
      v_actor_name, v_actor_name, v_now
    ) returning id into v_return_visit_id;
    v_created := true;
  end if;

  if (p_first_result is not null or v_memo <> '') and not exists (
    select 1 from public.return_visit_logs l
    where l.return_visit_id = v_return_visit_id
      and l.created_by = v_actor_name
      and l.result is not distinct from p_first_result
      and coalesce(l.memo, '') = v_memo
      and l.visited_at::date = v_now::date
  ) then
    insert into public.return_visit_logs (return_visit_id, visited_at, result, memo, created_by)
    values (v_return_visit_id, v_now, p_first_result, v_memo, v_actor_name);
  end if;

  if p_first_result is not null then
    update public.return_visits
    set last_visited_at = v_now, last_result = p_first_result
    where id = v_return_visit_id;
  end if;

  return jsonb_build_object(
    'id', v_return_visit_id,
    'created', v_created,
    'reactivated', v_reactivated,
    'unit_id', p_unit_id,
    'building_id', v_building_id
  );
end;
$$;

revoke all on function public.create_return_visit_tx(uuid,text,text,text,text,bigint)
  from public, anon, authenticated;
grant execute on function public.create_return_visit_tx(uuid,text,text,text,text,bigint)
  to anon, authenticated;

notify pgrst, 'reload schema';
