-- 장소 변경은 큰 원본 표가 아니라 작은 신호 표 한 행만 Realtime으로 보낸다.
-- 삭제 RPC와 신호 INSERT는 같은 트랜잭션이므로 둘 중 하나만 반영될 수 없다.

create table if not exists public.place_change_signals (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('deleted')),
  target_type text not null check (target_type in ('building', 'unit')),
  building_id bigint,
  unit_id bigint,
  unit_ids bigint[] not null default '{}',
  return_visit_ids bigint[] not null default '{}',
  created_at timestamptz not null default now()
);

alter table public.place_change_signals enable row level security;
alter table public.place_change_signals replica identity full;
revoke all on public.place_change_signals from public, anon, authenticated;
grant select on public.place_change_signals to anon, authenticated;

drop policy if exists place_change_signals_select on public.place_change_signals;
create policy place_change_signals_select on public.place_change_signals
  for select to anon, authenticated using (true);

do $$
begin
  if exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'buildings'
  ) then
    alter publication supabase_realtime drop table public.buildings;
  end if;
  if exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'units'
  ) then
    alter publication supabase_realtime drop table public.units;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'place_change_signals'
  ) then
    alter publication supabase_realtime add table public.place_change_signals;
  end if;
end $$;

create or replace function private.queue_place_deletion_signal(
  p_target_type text,
  p_target_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_building_id bigint;
  v_unit_id bigint;
  v_unit_ids bigint[] := '{}';
  v_return_visit_ids bigint[] := '{}';
begin
  if p_target_type = 'building' then
    v_building_id := p_target_id;
    select coalesce(array_agg(u.id::bigint order by u.id), '{}')
      into v_unit_ids
      from public.units u
      where u.building_id = p_target_id;
    select coalesce(array_agg(distinct rv.id::bigint order by rv.id::bigint), '{}')
      into v_return_visit_ids
      from public.return_visits rv
      where rv.building_id = p_target_id
         or rv.unit_id = any(v_unit_ids);
  elsif p_target_type = 'unit' then
    v_unit_id := p_target_id;
    v_unit_ids := array[p_target_id];
    select u.building_id into v_building_id
      from public.units u where u.id = p_target_id;
    select coalesce(array_agg(rv.id::bigint order by rv.id), '{}')
      into v_return_visit_ids
      from public.return_visits rv
      where rv.unit_id = p_target_id;
  else
    raise exception '삭제 대상 종류가 올바르지 않습니다';
  end if;

  insert into public.place_change_signals (
    action, target_type, building_id, unit_id, unit_ids, return_visit_ids
  ) values (
    'deleted', p_target_type, v_building_id, v_unit_id, v_unit_ids, v_return_visit_ids
  );
end;
$$;

revoke all on function private.queue_place_deletion_signal(text,bigint)
  from public, anon, authenticated;

create or replace function public.delete_place_or_request_tx(
  p_token uuid,
  p_target_type text,
  p_target_id bigint,
  p_request_type text default null,
  p_note text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id integer;
  v_actor_role text;
  v_exists boolean;
  v_has_links boolean;
  v_request jsonb;
  v_existing_request_id bigint;
begin
  v_actor_id := public.verify_session(p_token);
  select role into v_actor_role from public.app_users where id = v_actor_id;
  if p_target_type not in ('building', 'unit') then
    raise exception '삭제 대상 종류가 올바르지 않습니다';
  end if;

  if p_target_type = 'building' then
    select exists(select 1 from public.buildings where id = p_target_id) into v_exists;
  else
    select exists(select 1 from public.units where id = p_target_id) into v_exists;
  end if;
  if not v_exists then raise exception '장소를 찾을 수 없습니다'; end if;

  v_has_links := private.place_has_linked_data(p_target_type, p_target_id);
  if v_actor_role = 'user' or v_has_links then
    select id into v_existing_request_id
    from public.place_change_requests
    where status = 'pending'
      and request_type = 'remove_place'
      and (
        (p_target_type = 'unit' and unit_id = p_target_id)
        or (p_target_type = 'building' and building_id = p_target_id and unit_id is null)
      )
    order by id desc limit 1;
    if v_existing_request_id is not null then
      update public.place_change_requests
      set impact_snapshot = private.place_impact_snapshot(p_target_type, p_target_id)
      where id = v_existing_request_id;
      return jsonb_build_object(
        'ok', true, 'action', 'requested', 'request_id', v_existing_request_id,
        'has_linked_data', v_has_links, 'already_requested', true
      );
    end if;

    v_request := public.submit_place_change_request_tx(
      p_token,
      'remove_place',
      case when p_target_type = 'building' then p_target_id else null end,
      case when p_target_type = 'unit' then p_target_id else null end,
      null,
      p_note
    );
    return jsonb_build_object(
      'ok', true, 'action', 'requested', 'request_id', v_request -> 'id',
      'has_linked_data', v_has_links
    );
  end if;

  if not coalesce(v_actor_role in ('leader', 'admin', 'developer'), false) then
    raise exception '장소를 삭제할 권한이 없습니다' using errcode = '42501';
  end if;

  perform private.queue_place_deletion_signal(p_target_type, p_target_id);
  if p_target_type = 'unit' then
    delete from public.units where id = p_target_id;
  else
    delete from public.buildings where id = p_target_id;
  end if;
  return jsonb_build_object('ok', true, 'action', 'deleted', 'has_linked_data', false);
end;
$$;

revoke all on function public.delete_place_or_request_tx(uuid,text,bigint,text,text)
  from public, anon, authenticated;
grant execute on function public.delete_place_or_request_tx(uuid,text,bigint,text,text)
  to anon, authenticated;

create or replace function public.execute_place_deletion_request_tx(
  p_token uuid,
  p_request_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id integer;
  v_actor_name text;
  v_actor_role text;
  v_request public.place_change_requests%rowtype;
  v_target_type text;
  v_target_id bigint;
  v_impact jsonb;
begin
  v_actor_id := public.verify_session(p_token);
  select name, role into v_actor_name, v_actor_role from public.app_users where id = v_actor_id;
  if not coalesce(v_actor_role in ('admin', 'developer'), false) then
    raise exception '관리자만 장소 삭제를 확정할 수 있습니다' using errcode = '42501';
  end if;

  select * into v_request from public.place_change_requests
  where id = p_request_id and status = 'pending'
  for update;
  if not found then raise exception '처리할 삭제 요청을 찾을 수 없습니다'; end if;
  if v_request.request_type <> 'remove_place' then
    raise exception '장소 삭제 요청이 아닙니다';
  end if;

  if v_request.unit_id is not null then
    v_target_type := 'unit';
    v_target_id := v_request.unit_id;
  elsif v_request.building_id is not null then
    v_target_type := 'building';
    v_target_id := v_request.building_id;
  else
    raise exception '삭제할 장소가 이미 없거나 연결이 끊겼습니다';
  end if;

  v_impact := private.place_impact_snapshot(v_target_type, v_target_id);
  perform private.queue_place_deletion_signal(v_target_type, v_target_id);
  if v_target_type = 'unit' then
    delete from public.units where id = v_target_id;
  else
    delete from public.buildings where id = v_target_id;
  end if;
  if not found then raise exception '삭제할 장소가 이미 없습니다'; end if;

  update public.place_change_requests
  set status = 'completed',
      impact_snapshot = v_impact,
      reviewed_by_name = v_actor_name,
      review_note = '삭제 실행',
      reviewed_at = now()
  where id = p_request_id;

  return jsonb_build_object('ok', true, 'action', 'deleted', 'impact', v_impact);
end;
$$;

revoke all on function public.execute_place_deletion_request_tx(uuid,bigint)
  from public, anon, authenticated;
grant execute on function public.execute_place_deletion_request_tx(uuid,bigint)
  to anon, authenticated;

do $$
begin
  if exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public'
      and tablename in ('buildings', 'units')
  ) then
    raise exception '원본 장소 표가 Realtime publication에 남았습니다';
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public'
      and tablename = 'place_change_signals'
  ) then
    raise exception 'place_change_signals가 Realtime publication에 없습니다';
  end if;
  if has_table_privilege('anon', 'public.place_change_signals', 'INSERT,UPDATE,DELETE,TRUNCATE') then
    raise exception 'anon이 장소 변경 신호를 쓸 수 있습니다';
  end if;
end $$;

notify pgrst, 'reload schema';
